ktor:
  application:
    modules:
      - angrymiaucino.ApplicationKt.module
  deployment:
    port: 8080

r2dbc:
  url: "r2dbc:postgresql://postgres:12345@localhost:5432/postgres"  # Ensure the entire URL is quoted